name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: coverage run --branch --source=src --omit=**/__init__.py -m unittest
      - name: Show coverage report
        run: coverage report
      - name: Run linter
        run: pylint src
      - name: Run type checker
        run: mypy --ignore-missing-imports src
      - name: Run coding style checker
        run: pycodestyle src
